### ISSUE TITLE
F-F_Momentum_Factor does not work

### ISSUE THREAD

**Issue by AsafManela** [tbeason/FamaFrenchData.jl#22]
```julia
julia> readFamaFrench("F-F_Momentum_Factor")
(DataFrames.DataFrame[0×3 DataFrame
], [""], "F-F_Momentum_Factor.CSV  \nThis file was created by CMPT_ME_PRIOR_RETS using the 202006 CRSP database.  Itcontains a momentum factor, constructed from six value-weight portfolios formed")
```

Thanks for writing a very useful package!

**Comment by tbeason** [comment]
What an absolute mess that file is! Thanks for letting me know. I'll probably just have to add a special case for that one temporarily.

**Comment by tbeason** [comment]
This should be working now. I had a pretty simple rule for detecting tables, but this case showed how inadequate it was. I fixed it up to be much more explicit about detecting tables vs spurious commas. Should be much more robust. I registered a new version, once TagBot runs again you should be able to update and get the expected behavior.
